// Generated by CoffeeScript 1.6.3
(function() {
  var Client;

  Client = (function() {
    function Client() {}

    Client.prototype._get = function(path, params, cb) {
      this.calledVerb = 'get';
      this.calledPath = path;
      return this.calledData = params;
    };

    Client.prototype._post = function(path, data, cb) {
      this.calledVerb = 'post';
      this.calledPath = path;
      return this.calledData = data;
    };

    Client.prototype._put = function(path, data, cb) {
      this.calledVerb = 'put';
      this.calledPath = path;
      return this.calledData = data;
    };

    Client.prototype.verb = function() {
      return this.calledVerb;
    };

    Client.prototype.path = function() {
      return this.calledPath;
    };

    Client.prototype.data = function() {
      return this.calledData;
    };

    return Client;

  })();

  module.exports = Client;

}).call(this);
