// Generated by CoffeeScript 1.6.3
(function() {
  var Build;

  Build = (function() {
    function Build(client) {
      this.client = client;
    }

    Build.prototype.info = function(id, cb) {
      return this.client._get("/builds/" + this.id, null, cb);
    };

    Build.prototype.all = function() {
      return this.client._get('/builds', null, cb);
    };

    Build.prototype.locate = function(locator, cb) {
      console.log('locating');
      return this.client._get('/builds', {
        locator: locator.compile()
      }, cb);
    };

    return Build;

  })();

  module.exports = Build;

}).call(this);
