// Generated by CoffeeScript 1.6.3
(function() {
  var Build, BuildQueue, BuildTypes, Change, Client, Projects, VcsRootInstance, request;

  request = require('request');

  Build = require('./build');

  BuildTypes = require('./build-types');

  BuildQueue = require('./build-queue');

  Projects = require('./projects');

  Change = require('./change');

  VcsRootInstance = require('./vcs-root-instance');

  Client = (function() {
    function Client(options) {
      if (options.username && options.password) {
        this.auth = {
          username: options.username,
          password: options.password
        };
      }
      this.protocol = options.protocol || 'https';
      this.baseUrl = options.baseUrl || 'localhost:8080';
    }

    Client.prototype._url = function(path) {
      return "" + this.protocol + "://" + this.baseUrl + "/app/rest" + path;
    };

    Client.prototype._attachAuth = function(options) {
      if (this.auth) {
        return options.auth = {
          username: this.auth.username,
          password: this.auth.password,
          sendImmediately: true
        };
      }
    };

    Client.prototype._call = function(options, cb) {
      this._attachAuth(options);
      return request(options, function(err, response, body) {
        var data, error;
        if (!cb) {
          return;
        }
        if (err) {
          cb(err);
        }
        if (typeof body === 'string') {
          try {
            data = JSON.parse(body);
          } catch (_error) {
            error = _error;
            err = body;
          }
        } else {
          data = body;
        }
        return cb(err, data);
      });
    };

    Client.prototype._get = function(path, params, cb) {
      var options;
      console.log(path, params);
      options = {
        method: 'GET',
        url: this._url(path),
        headers: {
          'Accept': 'application/json'
        }
      };
      if (typeof params === 'function') {
        cb = params;
      } else {
        options.qs = params;
      }
      return this._call(options, cb);
    };

    Client.prototype._post = function(path, data, cb) {
      var options;
      options = {
        method: 'POST',
        url: this._url(path),
        json: data,
        headers: {
          'Accept': 'application/json'
        }
      };
      return this._call(options, cb);
    };

    Client.prototype._put = function(path, data, cb) {
      var options;
      options = {
        method: 'PUT',
        url: this._url(path),
        json: data,
        headers: {
          'Accept': 'application/json'
        }
      };
      return this._call(options, cb);
    };

    Client.prototype.projects = new Projects(Client);

    Client.prototype.buildTypes = new BuildTypes(Client);

    Client.prototype.builds = new Build(Client);

    Client.prototype.buildQueue = function() {
      return new BuildQueue(this);
    };

    Client.prototype.change = function() {
      return new Change(this);
    };

    Client.prototype.vcsRootInstance = function() {
      return new VcsRootInstance(this);
    };

    return Client;

  })();

  module.exports = Client;

}).call(this);
