// Generated by CoffeeScript 1.6.3
(function() {
  var BuildLocator, BuildTypeLocator, ChangesLocator, Client, ProjectLocator;

  Client = require('./client');

  ProjectLocator = require('./locators/project-locator');

  ChangesLocator = require('./locators/changes-locator');

  BuildLocator = require('./locators/build-locator');

  BuildTypeLocator = require('./locators/build-type-locator');

  module.exports = {
    client: function(options) {
      return new Client(options);
    },
    projectLocator: function() {
      return new ProjectLocator;
    },
    changesLocator: function() {
      return new ChangesLocator;
    },
    buildLocator: function() {
      return new BuildLocator;
    },
    buildTypeLocator: function() {
      return new BuildTypeLocator;
    }
  };

}).call(this);
